name: deploy_frontend
# Deploys with a push within /frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name azureresumestoragejn --auth-mode key -d '$web' -s frontend/
      - name: Purge cache in Cloudflare
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}

          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
